/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoftSkillsRouteImport } from './routes/soft-skills'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ObjetivoCarreiraRouteImport } from './routes/objetivo-carreira'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as ContribuicoesRouteImport } from './routes/contribuicoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const SoftSkillsRoute = SoftSkillsRouteImport.update({
  id: '/soft-skills',
  path: '/soft-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjetivoCarreiraRoute = ObjetivoCarreiraRouteImport.update({
  id: '/objetivo-carreira',
  path: '/objetivo-carreira',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContribuicoesRoute = ContribuicoesRouteImport.update({
  id: '/contribuicoes',
  path: '/contribuicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contribuicoes': typeof ContribuicoesRoute
  '/metas': typeof MetasRoute
  '/objetivo-carreira': typeof ObjetivoCarreiraRoute
  '/roadmap': typeof RoadmapRoute
  '/soft-skills': typeof SoftSkillsRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contribuicoes': typeof ContribuicoesRoute
  '/metas': typeof MetasRoute
  '/objetivo-carreira': typeof ObjetivoCarreiraRoute
  '/roadmap': typeof RoadmapRoute
  '/soft-skills': typeof SoftSkillsRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contribuicoes': typeof ContribuicoesRoute
  '/metas': typeof MetasRoute
  '/objetivo-carreira': typeof ObjetivoCarreiraRoute
  '/roadmap': typeof RoadmapRoute
  '/soft-skills': typeof SoftSkillsRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contribuicoes'
    | '/metas'
    | '/objetivo-carreira'
    | '/roadmap'
    | '/soft-skills'
    | '/admin/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contribuicoes'
    | '/metas'
    | '/objetivo-carreira'
    | '/roadmap'
    | '/soft-skills'
    | '/admin/login'
  id:
    | '__root__'
    | '/'
    | '/contribuicoes'
    | '/metas'
    | '/objetivo-carreira'
    | '/roadmap'
    | '/soft-skills'
    | '/admin/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContribuicoesRoute: typeof ContribuicoesRoute
  MetasRoute: typeof MetasRoute
  ObjetivoCarreiraRoute: typeof ObjetivoCarreiraRoute
  RoadmapRoute: typeof RoadmapRoute
  SoftSkillsRoute: typeof SoftSkillsRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soft-skills': {
      id: '/soft-skills'
      path: '/soft-skills'
      fullPath: '/soft-skills'
      preLoaderRoute: typeof SoftSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objetivo-carreira': {
      id: '/objetivo-carreira'
      path: '/objetivo-carreira'
      fullPath: '/objetivo-carreira'
      preLoaderRoute: typeof ObjetivoCarreiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribuicoes': {
      id: '/contribuicoes'
      path: '/contribuicoes'
      fullPath: '/contribuicoes'
      preLoaderRoute: typeof ContribuicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContribuicoesRoute: ContribuicoesRoute,
  MetasRoute: MetasRoute,
  ObjetivoCarreiraRoute: ObjetivoCarreiraRoute,
  RoadmapRoute: RoadmapRoute,
  SoftSkillsRoute: SoftSkillsRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
